SchoolSystem/Controllers/senddatafromviewController.cs
using SchoolSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace SchoolSystem.Controllers
{
    public class senddatafromviewController : Controller
    {
        // GET: senddatafromview
        public ActionResult senddatausingparameter(string FirstName,string Lastname)
        {
            string mydetails = "First Name" + FirstName + "|Last Name" + Lastname;
            if(!FirstName.IsEmpty() && ! Lastname.IsEmpty()) 
            ViewBag.mydtails = mydetails;
            return View();
        }
        public string SenddatausingRequest()
        {
            string FN = Request["FirstName"];
            string LN = Request["LastName"];
            string mydetails = "First Name" + FN + "|Last Name" + LN;
            
            return mydetails;
        }
        public ActionResult senddatausingbinding(simple_name SN)
        {
            string FN = SN.firstname;
            string LN = SN.lastname;
            ViewBag.Myproperty = FN;
            ViewData["Myproperty"] = LN;
            return View();
        }

    }
}

SchoolSystem/Views/senddatafromview/senddatausingbinding.cshtml
@{
    ViewBag.Title = "senddatausingbinding";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>senddatausingbinding</h2>
<div>
    <table>
        <tr>
            <td>
                FirstName:
            </td>
            <td>
                @ViewBag.Myproperty
            </td>
        </tr>
        <tr>
            <td>
                LastName:
            </td>
            <td>@ViewData["Myproperty"] </td>
        </tr>
       </table>
</div>

SchoolSystem/Views/senddatafromview/senddatausingparameter.cshtml
@model SchoolSystem.Models.simple_name
@{
    ViewBag.Title = "senddatausingparameter";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>senddatausingparameter</h2>
<div>
    <section>
        @using (Html.BeginForm("senddatausingparameter", "senddatafromview"))
        {
            <table class="table">
                <tr>
                    <td colspan="2">Send Data using Parameter</td>
                </tr>
                <tr>
                    <td>First Name</td>
                    <td>
                        <input type="text" name="FirstName" />
                    </td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td> <input type="text" name="LastName" /></td>
                </tr>
                <tr>
                    <td><input type="submit" value="sendusingparameter" /></td>
                </tr>
            </table>
        }
    </section>

</div>
<div>
    <h3>@ViewBag.mydtails</h3>

</div>
<br />
<h2>senddatausingparameter</h2>
<div>
    <section>
        @using (Html.BeginForm("SenddatausingRequest", "senddatafromview",FormMethod.Post))
        {
            <table class="table">
                <tr>
                    <td colspan="2">Send Data using Request</td>
                </tr>
                <tr>
                    <td>First Name</td>
                    <td>
                        @Html.TextBoxFor(x=>x.firstname)
                    </td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td>
                        @Html.TextBoxFor(x => x.lastname)

                    </td>
                </tr>
                <tr>
                    <td><input type="submit" value="sendusingrequest" /></td>
                </tr>
            </table>
        }
    </section>

</div>
<div>
    <h3>@ViewBag.mydtails</h3>

</div>
<br />
<div>
    <section>
        @using (Html.BeginForm("senddatausingbinding", "senddatafromview"))
        {
            <table class="table">
                <tr>
                    <td colspan="2">Send Data using binding</td>
                </tr>
                <tr>
                    <td>First Name</td>
                    <td>
                        <input type="text" name="FirstName" />
                    </td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td> <input type="text" name="LastName" /></td>
                </tr>
                <tr>
                    <td><input type="submit" value="sendusingbinding" /></td>
                </tr>
            </table>
        }
    </section>

</div>